### ISSUE TITLE
CI Pipeline für Monitoring-Tests fehlt

### ISSUE THREAD

**Issue by Jedimind369** [Jedimind369/bookmark-master#2]
## Problem

Die CI-Pipeline für die Monitoring-Tests schlägt fehl, da die Datei `.github/workflows/ci_pipeline.yml` leer ist. Der Fehler tritt bei jedem Push auf den Branch `features/hybrid-optimization` auf.

## Lösung

Eine neue CI-Pipeline-Konfiguration muss erstellt werden. Hier ist der vorgeschlagene Inhalt für die Datei:

```yaml
name: API Monitoring CI

on:
  push:
    branches: [ main, develop, 'features/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Vollständige Git-History für korrekte Tests
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-asyncio
    
    - name: Install monitoring dependencies
      run: |
        pip install streamlit pandas plotly altair matplotlib
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Create data directories
      run: |
        mkdir -p data/monitoring/backups
    
    - name: Run backup functionality tests
      run: |
        python -m scripts.monitoring.test_monitoring --backup --days 3
    
    - name: Run GitHub sync tests
      run: |
        python -m scripts.monitoring.test_github_sync --no-backup
    
    - name: Check backup files integrity
      run: |
        # Prüft, ob generierte Backup-Dateien vorhanden sind
        if [ -z "$(ls -A data/monitoring/backups)" ]; then
          echo "Keine Backup-Dateien gefunden!"
          exit 1
        else
          echo "Backup-Dateien erfolgreich erstellt"
          ls -la data/monitoring/backups
        fi
    
    - name: Validate monitoring data structure
      run: |
        # Prüft, ob die Nutzungsdatei korrekt erzeugt wurde
        if [ ! -f "data/monitoring/api_usage.json" ]; then
          echo "API-Nutzungsdatei nicht gefunden!"
          exit 1
        else
          echo "API-Nutzungsdatei erfolgreich erstellt"
          cat data/monitoring/api_usage.json
        fi
    
    - name: Push test backup to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: monitoring-backups
        path: data/monitoring/backups/
        retention-days: 7
```

Diese Pipeline testet die Backup-Funktionalität und die GitHub-Synchronisation des Monitoring-Systems. Sie prüft auch die Integrität der erzeugten Backup-Dateien und validiert die Datenstruktur.

**Hinweis:** Die Datei kann nicht direkt über die API erstellt werden, sondern muss von einem Benutzer mit den entsprechenden Berechtigungen im Repository hinzugefügt werden.

## Warum diese Änderung?

Mit dieser CI-Pipeline können wir automatisch testen, ob die Monitoring-Funktionalität wie erwartet funktioniert, insbesondere:
1. Backup-Erstellung und -Wiederherstellung
2. GitHub-Synchronisation
3. Integritätsprüfung der Backups
4. Speicherung und Validierung der API-Nutzungsdaten

Diese Tests sind wichtig, um sicherzustellen, dass alle Überwachungs- und Sicherungsfunktionen für die API-Kostenüberwachung korrekt funktionieren.
